"""
Minimal, dependency-free SQL migration runner. Applies every .sql file in this
directory (sorted by filename, so name migrations "0001_...", "0002_..." etc.) that
hasn't already been recorded in the schema_migrations table, one transaction per file.

This intentionally does not pull in a full migration framework (Alembic, etc.) - at
this project's size, a table of applied filenames and a for-loop is the whole feature,
and it's easy to read top to bottom. Revisit this decision if migrations start needing
things this can't do (branching/merging, autogenerated diffs from ORM models).
"""
import logging
import os

import psycopg

logger = logging.getLogger("atlas.migrations")

MIGRATIONS_DIR = os.path.dirname(os.path.abspath(__file__))


def run_migrations(database_url: str) -> None:
    with psycopg.connect(database_url, autocommit=True) as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS schema_migrations (
                filename TEXT PRIMARY KEY,
                applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """
        )
        applied = {row[0] for row in conn.execute("SELECT filename FROM schema_migrations").fetchall()}

        pending = sorted(
            f for f in os.listdir(MIGRATIONS_DIR)
            if f.endswith(".sql") and f not in applied
        )
        for filename in pending:
            path = os.path.join(MIGRATIONS_DIR, filename)
            with open(path, "r") as f:
                sql = f.read()
            logger.info("applying migration %s", filename)
            with conn.transaction():
                conn.execute(sql)
                conn.execute("INSERT INTO schema_migrations (filename) VALUES (%s)", (filename,))
